version: "3.9"
services:

  db: 
    image: postgres:latest
    container_name: postgres-database
    restart: always
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=policydb
    networks:
      backend-server:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/1-database.sql
      - ./scripts/refresh_sample_data.sql:/docker-entrypoint-initdb.d/2-refresh_sample_data.sql

  db-admin:
    image: dpage/pgadmin4:latest
    container_name: postgres-database-admin
    restart: always
    networks:
      - backend-server
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=admin
    depends_on:
      - db
    ports:
      - "8080:80"

  server:
    build: 
      context: .
    container_name: truth-loop-server
    restart: always
    networks:
      - backend-server
    depends_on:
      - db
    ports:
      - "5000:5000"
      
networks:
  backend-server: